print("MACRO")

game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("[Loading Macro..]","all")
wait(3.0)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("[Macro has loaded!","all")
wait(0.5)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("[Macro is made by cvurid.]","all")
game.Players.LocalPlayer.Chatted:connect(function(cmd)
end)

StarterGui = game:GetService("StarterGui") StarterGui:SetCore("TopbarEnabled", false)

game:GetService("StarterGui"):SetCore("SendNotification", {
  Title = "MACRO",
  Text = "Macro is made by cvurid."})

wait(0.4)

StarterGui = game:GetService("StarterGui") StarterGui:SetCore("TopbarEnabled", true)

print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
print("MACRO")
print("MACRO") 
